### ISSUE TITLE
Evaluate Synthetic Rating Curves

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#203]
This agile story will include all efforts relating to the evaluation of synthetic rating curves (SRCs).

## Tasks
- [ ] Develop automated test to characterize SRC bias (#)
- [ ] Compute contingency tables through "binning" of SRC error (#)
- [ ] Develop capability deliver SRC performance metrics to web service (#)
