### ISSUE TITLE
Agile Story: Test prototype solutions for representing channel bathymetry in synthetic rating curves

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/cahaba#306]
Continuation of agile story from previous sprint (see card #282)

Explore solutions to account for known issue of missing channel bathymetry (FIM over-estimation at < minor flood conditions). The current solution incorporates regression-based channel bankfull geometry estimates to quantify the missing bathymetric component not represented in the DEM and resulting synthetic rating curve.

- [x]  [5pt] Develop SRC workaround solution for thalweg burn notch (Issue #309)
- [x] [3pt] Test that current feature branch solution is cable of running for large subset of HUCS (Issue #310)
- [x]  [3pt] Perform alpha evaluation for subset of HUCS (Issue #311)
- [x] [3pt] Create user input flag on/off option for bathy estimation calculation (submit PR) (Issue #328)
- [x] [5pt] Create slide deck content to document alpha eval performance
- [x] [2pt] Attempt CONUS MS simulation with bathy feature branch (Issue #330)
