### ISSUE TITLE
Mechanism to automatically adjust synthetic rating curves given field feedback

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [NOAA-OWP/cahaba#436]
Proposed feature would ingest spatial points depicting known FIM boundary and use point locations to modify synthetic rating curves for relevant catchments to yield better matching inundation extents. A dummy spatial file may be used for testing.

The fields `HydraulicRadius (m)`, `WetArea (m2)`, `SLOPE`, `ManningN` will be used to programmatically update the SRC json file, so these three variables will need to be added to `Hyrotable.csv`. This can be done in `add_crosswalk.py` (line 223).

- [x] Write function to extract HAND and hydroid at any given point, as determined by a shapefile (#437)
- [x] Determine the median HAND value for each relevant Hydroid (#437)
- [x] Use median HAND value, flow, and hydroid and read in wetted area, hydraulic radius, and feature_id to perform the SRC adjustment (#)
- [x] Copy default flow and N columns to new columns and give new name, overwrite official columns with the new calculated values, also add `last_updated` and `submitter` columns

**Comment by BradfordBates-NOAA** [comment]
Recommended Hydrotable 
![image](https://user-images.githubusercontent.com/69594899/127371072-8cf3b19b-732e-448a-a522-faadafea4b60.png)

**Comment by BradfordBates-NOAA** [comment]
```python foss_fim/tools/adjust_rc_with_feedback.py -p /data/temp/water_edge_rc_adjust/known_water_edge.shp -d /data/outputs/point_adjust/aggregate_fim_outputs/ -w /data/temp/water_edge_rc_adjust/WBD_National_copy.gpkg```
